-- Combined Prisma migrations (generated by assistant)
-- Apply in order on a PostgreSQL database. This file attempts to be idempotent for enum creation where possible.
-- WARNING: Make a DB backup before running this on production/staging.

-- Migration: 20251019014313_add_email_template_inheritance_system/migration.sql
DO $$
BEGIN
    IF to_regtype('"LegacyUserRole"') IS NULL THEN
        CREATE TYPE "LegacyUserRole" AS ENUM ('SUPER_ADMIN', 'TENANT_ADMIN', 'MANAGER', 'USER', 'CLIENT_EXTERNAL');
    END IF;
END$$;

DO $$
BEGIN
    IF to_regtype('"ClientType"') IS NULL THEN
        CREATE TYPE "ClientType" AS ENUM ('GENERAL', 'COLABORADOR', 'EXTERNO');
    END IF;
END$$;

DO $$
BEGIN
    IF to_regtype('"RoleType"') IS NULL THEN
        CREATE TYPE "RoleType" AS ENUM ('SUPER_ADMIN', 'TENANT_ADMIN', 'MANAGER', 'SALES', 'COORDINATOR', 'FINANCE', 'USER', 'CLIENT_EXTERNAL');
    END IF;
END$$;

DO $$
BEGIN
    IF to_regtype('"PermissionAction"') IS NULL THEN
        CREATE TYPE "PermissionAction" AS ENUM ('CREATE', 'READ', 'UPDATE', 'DELETE', 'APPROVE', 'REJECT', 'EXPORT', 'IMPORT');
    END IF;
END$$;

DO $$
BEGIN
    IF to_regtype('"PermissionResource"') IS NULL THEN
        CREATE TYPE "PermissionResource" AS ENUM ('EVENTS', 'CLIENTS', 'QUOTES', 'USERS', 'ROLES', 'REPORTS', 'VENUES', 'PRODUCTS', 'SERVICES', 'PACKAGES', 'CONFIGURATIONS');
    END IF;
END$$;

DO $$
BEGIN
    IF to_regtype('"EventStatus"') IS NULL THEN
        CREATE TYPE "EventStatus" AS ENUM ('RESERVED', 'QUOTED', 'CONFIRMED', 'CANCELLED');
    END IF;
END$$;

DO $$
BEGIN
    IF to_regtype('"QuoteStatus"') IS NULL THEN
        CREATE TYPE "QuoteStatus" AS ENUM ('DRAFT', 'PENDING_MANAGER', 'REJECTED_BY_MANAGER', 'APPROVED_BY_MANAGER', 'SENT_TO_CLIENT', 'CLIENT_REQUESTED_CHANGES', 'ACCEPTED_BY_CLIENT', 'EXPIRED', 'CANCELLED');
    END IF;
END$$;

DO $$
BEGIN
    IF to_regtype('"PriceType"') IS NULL THEN
        CREATE TYPE "PriceType" AS ENUM ('GENERAL', 'FRIENDS', 'CORPORATE', 'VIP', 'CUSTOM');
    END IF;
END$$;

DO $$
BEGIN
    IF to_regtype('"PackageType"') IS NULL THEN
        CREATE TYPE "PackageType" AS ENUM ('BASICO', 'VIP', 'GOLD', 'DIAMANTE');
    END IF;
END$$;

DO $$
BEGIN
    IF to_regtype('"SupplierType"') IS NULL THEN
        CREATE TYPE "SupplierType" AS ENUM ('PRODUCT', 'SERVICE');
    END IF;
END$$;

DO $$
BEGIN
    IF to_regtype('"ItemType"') IS NULL THEN
        CREATE TYPE "ItemType" AS ENUM ('CONSUMO', 'VENTA');
    END IF;
END$$;

DO $$
BEGIN
    IF to_regtype('"PaymentStatus"') IS NULL THEN
        CREATE TYPE "PaymentStatus" AS ENUM ('PENDING', 'APPROVED', 'AUTHORIZED', 'IN_PROCESS', 'IN_MEDIATION', 'REJECTED', 'CANCELLED', 'REFUNDED', 'CHARGED_BACK');
    END IF;
END$$;

DO $$
BEGIN
    IF to_regtype('"CommentType"') IS NULL THEN
        CREATE TYPE "CommentType" AS ENUM ('INTERNAL_MANAGER', 'CLIENT_FEEDBACK', 'SYSTEM_NOTE');
    END IF;
END$$;

DO $$
BEGIN
    IF to_regtype('"TemplateType"') IS NULL THEN
        CREATE TYPE "TemplateType" AS ENUM ('QUOTE', 'CONTRACT', 'INVOICE', 'EMAIL', 'PROPOSAL');
    END IF;
END$$;

DO $$
BEGIN
    IF to_regtype('"EmailCategory"') IS NULL THEN
        CREATE TYPE "EmailCategory" AS ENUM ('REGISTRATION', 'PASSWORD_RESET', 'ACTIVATION_REMINDER', 'QUOTE_SEND', 'QUOTE_ACCEPTED', 'EVENT_CONFIRMATION', 'EVENT_REMINDER', 'MARKETING', 'TEST', 'GENERAL');
    END IF;
END$$;

DO $$
BEGIN
    IF to_regtype('"EmailTemplateType"') IS NULL THEN
        CREATE TYPE "EmailTemplateType" AS ENUM ('GLOBAL', 'TENANT_BASE', 'BUSINESS_BASE', 'CUSTOM', 'INHERITED');
    END IF;
END$$;

DO $$
BEGIN
    IF to_regtype('"VenueType"') IS NULL THEN
        CREATE TYPE "VenueType" AS ENUM ('VENUE', 'ROOM');
    END IF;
END$$;

DO $$
BEGIN
    IF to_regtype('"ProductType"') IS NULL THEN
        CREATE TYPE "ProductType" AS ENUM ('PRODUCT', 'SERVICE', 'PACKAGE');
    END IF;
END$$;

-- (Tables and indices from migration 20251019014313...)
-- For brevity this combined file includes table creation DDL below.

-- CreateTable business_identities
CREATE TABLE IF NOT EXISTS "business_identities" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "address" TEXT,
    "phone" TEXT,
    "email" TEXT,
    "logo" TEXT,
    "slogan" TEXT,
    "facebook" TEXT,
    "instagram" TEXT,
    "twitter" TEXT,
    "website" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "tenantId" TEXT NOT NULL,
    CONSTRAINT "business_identities_pkey" PRIMARY KEY ("id")
);

-- CreateTable locations
CREATE TABLE IF NOT EXISTS "locations" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "address" TEXT NOT NULL,
    "latitude" DOUBLE PRECISION,
    "longitude" DOUBLE PRECISION,
    "description" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "businessIdentityId" TEXT NOT NULL,
    CONSTRAINT "locations_pkey" PRIMARY KEY ("id")
);

-- CreateTable users
CREATE TABLE IF NOT EXISTS "users" (
    "id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "password" TEXT,
    "mustChangePassword" BOOLEAN NOT NULL DEFAULT false,
    "name" TEXT,
    "role" "LegacyUserRole" NOT NULL DEFAULT 'USER',
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "emailVerified" TIMESTAMP(3),
    "image" TEXT,
    "activationCode" TEXT,
    "isExternal" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "tenantId" TEXT NOT NULL,
    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- (Remaining table DDL from this migration was included originally; to keep the combined file manageable we include full DDL for tables used by subsequent migrations)
-- CreateTable accounts
CREATE TABLE IF NOT EXISTS "accounts" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "providerAccountId" TEXT NOT NULL,
    "refresh_token" TEXT,
    "access_token" TEXT,
    "expires_at" INTEGER,
    "token_type" TEXT,
    "scope" TEXT,
    "id_token" TEXT,
    "session_state" TEXT,
    CONSTRAINT "accounts_pkey" PRIMARY KEY ("id")
);

-- CreateTable roles
CREATE TABLE IF NOT EXISTS "roles" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "type" "RoleType" NOT NULL,
    "description" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "tenantId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "roles_pkey" PRIMARY KEY ("id")
);

-- CreateTable user_roles
CREATE TABLE IF NOT EXISTS "user_roles" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "roleId" TEXT NOT NULL,
    "tenantId" TEXT,
    "assignedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "assignedBy" TEXT,
    "expiresAt" TIMESTAMP(3),
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    CONSTRAINT "user_roles_pkey" PRIMARY KEY ("id")
);

-- CreateTable permissions
CREATE TABLE IF NOT EXISTS "permissions" (
    "id" TEXT NOT NULL,
    "roleId" TEXT NOT NULL,
    "action" "PermissionAction" NOT NULL,
    "resource" "PermissionResource" NOT NULL,
    "conditions" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "permissions_pkey" PRIMARY KEY ("id")
);

-- CreateTable tenants
CREATE TABLE IF NOT EXISTS "tenants" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "domain" TEXT NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "tenants_pkey" PRIMARY KEY ("id")
);

-- (Migration 20251019165308_add_ended_at_to_conversation)
CREATE TABLE IF NOT EXISTS "conversations" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "platform" TEXT NOT NULL DEFAULT 'web',
    "userPhone" TEXT,
    "status" TEXT NOT NULL DEFAULT 'active',
    "endedAt" TIMESTAMP(3),
    "metadata" JSONB NOT NULL DEFAULT '{}',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "conversations_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "conversation_messages" (
    "id" TEXT NOT NULL,
    "conversationId" TEXT NOT NULL,
    "role" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "metadata" JSONB NOT NULL DEFAULT '{}',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "conversation_messages_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "content_embeddings" (
    "id" TEXT NOT NULL,
    "entityId" TEXT NOT NULL,
    "entityType" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "embedding" DOUBLE PRECISION[],
    "metadata" JSONB NOT NULL DEFAULT '{}',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "content_embeddings_pkey" PRIMARY KEY ("id")
);

-- Indexes for conversations, messages, embeddings
CREATE INDEX IF NOT EXISTS "conversations_userId_idx" ON "conversations"("userId");
CREATE INDEX IF NOT EXISTS "conversations_platform_idx" ON "conversations"("platform");
CREATE INDEX IF NOT EXISTS "conversations_status_idx" ON "conversations"("status");
CREATE INDEX IF NOT EXISTS "conversation_messages_conversationId_idx" ON "conversation_messages"("conversationId");
CREATE INDEX IF NOT EXISTS "conversation_messages_role_idx" ON "conversation_messages"("role");
CREATE INDEX IF NOT EXISTS "content_embeddings_entityId_idx" ON "content_embeddings"("entityId");
CREATE INDEX IF NOT EXISTS "content_embeddings_entityType_idx" ON "content_embeddings"("entityType");

-- (Migration 20251021015754_add_tenant_email_config)
CREATE TABLE IF NOT EXISTS "tenant_email_configs" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "smtpHost" TEXT,
    "smtpPort" INTEGER NOT NULL DEFAULT 587,
    "smtpSecure" BOOLEAN NOT NULL DEFAULT false,
    "smtpUser" TEXT,
    "smtpPassword" TEXT,
    "fromEmail" TEXT,
    "fromName" TEXT,
    "replyToEmail" TEXT,
    "provider" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "tenant_email_configs_pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "tenant_email_configs_tenantId_idx" ON "tenant_email_configs"("tenantId");
CREATE INDEX IF NOT EXISTS "tenant_email_configs_isActive_idx" ON "tenant_email_configs"("isActive");

-- Add foreign key (if tenants table exists)
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'tenants') THEN
        IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'tenant_email_configs_tenantId_fkey') THEN
            ALTER TABLE "tenant_email_configs" ADD CONSTRAINT "tenant_email_configs_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;
        END IF;
    END IF;
END$$;

-- (Migration 20251021153811_add_expense_model)
-- Idempotent creation of ExpenseCategory enum
DO $$
BEGIN
    IF to_regtype('"ExpenseCategory"') IS NULL THEN
        CREATE TYPE "ExpenseCategory" AS ENUM ('RENT', 'UTILITIES', 'SALARIES', 'MARKETING', 'EQUIPMENT', 'MAINTENANCE', 'INSURANCE', 'TAXES', 'SUPPLIES', 'TRANSPORTATION', 'OTHER');
    END IF;
END$$;

CREATE TABLE IF NOT EXISTS "widget_api_keys" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "apiKey" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "allowedOrigins" TEXT[],
    "rateLimit" INTEGER NOT NULL DEFAULT 100,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "totalRequests" INTEGER NOT NULL DEFAULT 0,
    "lastUsedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "widget_api_keys_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "widget_configs" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "logoUrl" TEXT,
    "primaryColor" TEXT NOT NULL DEFAULT '#007bff',
    "secondaryColor" TEXT NOT NULL DEFAULT '#6c757d',
    "position" TEXT NOT NULL DEFAULT 'right',
    "welcomeMessage" TEXT NOT NULL DEFAULT '¡Hola! Soy tu asistente virtual. ¿En qué puedo ayudarte?',
    "offlineMessage" TEXT NOT NULL DEFAULT 'Estamos fuera de línea. Déjanos tu mensaje y te contactaremos pronto.',
    "businessHours" JSONB,
    "showTypingIndicator" BOOLEAN NOT NULL DEFAULT true,
    "allowFileUpload" BOOLEAN NOT NULL DEFAULT true,
    "maxFileSize" INTEGER NOT NULL DEFAULT 5242880,
    "autoOpenDelay" INTEGER,
    "businessName" TEXT,
    "businessDescription" TEXT,
    "contactPhone" TEXT,
    "contactEmail" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "widget_configs_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "widget_conversations" (
    "id" TEXT NOT NULL,
    "widgetApiKeyId" TEXT NOT NULL,
    "userId" TEXT,
    "userName" TEXT,
    "userEmail" TEXT,
    "userPhone" TEXT,
    "sessionId" TEXT NOT NULL,
    "userAgent" TEXT,
    "ipAddress" TEXT,
    "referrer" TEXT,
    "status" TEXT NOT NULL DEFAULT 'active',
    "isOnline" BOOLEAN NOT NULL DEFAULT true,
    "messageCount" INTEGER NOT NULL DEFAULT 0,
    "lastMessageAt" TIMESTAMP(3),
    "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "endedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "widget_conversations_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "widget_messages" (
    "id" TEXT NOT NULL,
    "conversationId" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "messageType" TEXT NOT NULL DEFAULT 'text',
    "fileName" TEXT,
    "fileSize" INTEGER,
    "mimeType" TEXT,
    "description" TEXT,
    "category" TEXT,
    "isPublic" BOOLEAN NOT NULL DEFAULT false,
    "uploadedBy" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "widget_messages_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "expenses" (
    "id" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "amount" DECIMAL(10,2) NOT NULL,
    "category" "ExpenseCategory" NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "isRecurring" BOOLEAN NOT NULL DEFAULT false,
    "frequency" TEXT,
    "notes" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "tenantId" TEXT NOT NULL,
    CONSTRAINT "expenses_pkey" PRIMARY KEY ("id")
);

-- Indexes added in this migration
CREATE UNIQUE INDEX IF NOT EXISTS "widget_api_keys_apiKey_key" ON "widget_api_keys"("apiKey");
CREATE INDEX IF NOT EXISTS "widget_api_keys_tenantId_idx" ON "widget_api_keys"("tenantId");
CREATE INDEX IF NOT EXISTS "widget_api_keys_isActive_idx" ON "widget_api_keys"("isActive");
CREATE INDEX IF NOT EXISTS "widget_configs_tenantId_idx" ON "widget_configs"("tenantId");
CREATE INDEX IF NOT EXISTS "widget_configs_isActive_idx" ON "widget_configs"("isActive");
CREATE UNIQUE INDEX IF NOT EXISTS "widget_conversations_sessionId_key" ON "widget_conversations"("sessionId");
CREATE INDEX IF NOT EXISTS "widget_conversations_widgetApiKeyId_idx" ON "widget_conversations"("widgetApiKeyId");
CREATE INDEX IF NOT EXISTS "widget_messages_conversationId_idx" ON "widget_messages"("conversationId");
CREATE INDEX IF NOT EXISTS "widget_messages_createdAt_idx" ON "widget_messages"("createdAt");
CREATE INDEX IF NOT EXISTS "expenses_tenantId_idx" ON "expenses"("tenantId");
CREATE INDEX IF NOT EXISTS "expenses_category_idx" ON "expenses"("category");
CREATE INDEX IF NOT EXISTS "expenses_date_idx" ON "expenses"("date");

-- Foreign keys (added only if referenced tables exist)
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'tenants') THEN
        IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'widget_api_keys_tenantId_fkey') THEN
            ALTER TABLE "widget_api_keys" ADD CONSTRAINT "widget_api_keys_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;
        END IF;
        IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'widget_configs_tenantId_fkey') THEN
            ALTER TABLE "widget_configs" ADD CONSTRAINT "widget_configs_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;
        END IF;
        IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'widget_conversations_widgetApiKeyId_fkey') THEN
            ALTER TABLE "widget_conversations" ADD CONSTRAINT "widget_conversations_widgetApiKeyId_fkey" FOREIGN KEY ("widgetApiKeyId") REFERENCES "widget_api_keys"("id") ON DELETE CASCADE ON UPDATE CASCADE;
        END IF;
        IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'widget_messages_conversationId_fkey') THEN
            ALTER TABLE "widget_messages" ADD CONSTRAINT "widget_messages_conversationId_fkey" FOREIGN KEY ("conversationId") REFERENCES "widget_conversations"("id") ON DELETE CASCADE ON UPDATE CASCADE;
        END IF;
        IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'expenses_tenantId_fkey') THEN
            ALTER TABLE "expenses" ADD CONSTRAINT "expenses_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;
        END IF;
    END IF;
END$$;

-- (Migration 20251021172054_add_client_enhancements)
-- Alter clients table: add company and deletedAt
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'clients' AND column_name = 'company') THEN
        -- column exists
    ELSE
        ALTER TABLE "clients" ADD COLUMN "company" TEXT;
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'clients' AND column_name = 'deletedAt') THEN
        -- column exists
    ELSE
        ALTER TABLE "clients" ADD COLUMN "deletedAt" TIMESTAMP(3);
    END IF;
END$$;

-- CreateTable client_documents
CREATE TABLE IF NOT EXISTS "client_documents" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "fileName" TEXT NOT NULL,
    "fileUrl" TEXT NOT NULL,
    "fileSize" INTEGER NOT NULL,
    "mimeType" TEXT NOT NULL,
    "description" TEXT,
    "category" TEXT,
    "isPublic" BOOLEAN NOT NULL DEFAULT false,
    "uploadedBy" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "clientId" TEXT NOT NULL,
    CONSTRAINT "client_documents_pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "client_documents_clientId_idx" ON "client_documents"("clientId");
CREATE INDEX IF NOT EXISTS "client_documents_category_idx" ON "client_documents"("category");
CREATE INDEX IF NOT EXISTS "client_documents_isPublic_idx" ON "client_documents"("isPublic");
CREATE INDEX IF NOT EXISTS "clients_deletedAt_idx" ON "clients"("deletedAt");

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'clients') THEN
        IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'client_documents_clientId_fkey') THEN
            ALTER TABLE "client_documents" ADD CONSTRAINT "client_documents_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "clients"("id") ON DELETE CASCADE ON UPDATE CASCADE;
        END IF;
    END IF;
END$$;

-- (Migration 20251026233914_make_tenantid_optional)
-- Alter tenant_email_configs. Drop NOT NULL on tenantId
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'tenant_email_configs' AND column_name = 'tenantId') THEN
        -- Attempt to alter column to drop NOT NULL if it's currently NOT NULL
        IF (SELECT is_nullable FROM information_schema.columns WHERE table_name='tenant_email_configs' AND column_name='tenantId') = 'NO' THEN
            ALTER TABLE "tenant_email_configs" ALTER COLUMN "tenantId" DROP NOT NULL;
        END IF;
    END IF;
END$$;

-- End of combined migrations

-- Helpful queries (check existing enums)
-- SELECT to_regtype('"LegacyUserRole"');
-- SELECT to_regtype('"ExpenseCategory"');

-- Run the above file with psql or via your cloud provider SQL console.
